image: docker:24.0.2

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "/certs/client"

services:
  - name: docker:24.0.2-dind
    alias: docker

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t cloud-tools ./tools/ -f image/Dockerfile

test:
  stage: test
  script:
    - docker compose up --exit-code-from cloud-test

deploy:
  stage: deploy
  only:
    - tags
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag cloud-tools $CI_REGISTRY/default/clouddev-env/cloud-tools:latest
    - docker tag cloud-tools $CI_REGISTRY/default/clouddev-env/cloud-tools:$CI_COMMIT_TAG
    - docker push cloud-tools $CI_REGISTRY/default/clouddev-env/cloud-tools:latest
    - docker push $CI_REGISTRY/default/clouddev-env/cloud-tools:$CI_COMMIT_TAG
