services:
  cloud-test:
    image: cloud-tools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test:/test
      - ./tools/versions.sh:/tools/versions.sh
    environment:
      - ENV_NAME=docker
    entrypoint:
      - python
      - /test/test_tool_versions.py
