services:
  cloud-test:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV_NAME=docker
    entrypoint:
      - python
      - /home/clouddev/src/test/test_tool_versions.py
