name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Build image
        run: docker build -t cloud-tools -f image/Dockerfile ./tools/
      - name: Test image
        run: docker compose up --exit-code-from cloud-test
      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "eseidinger/github"
          platforms: linux/amd64,linux/arm64
          install: true
      - name: Build and push
        id: build-docker
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          tags: "${{ vars.DOCKER_USER }}/cloud-tools:latest,${{ vars.DOCKER_USER }}/cloud-tools:${{ github.ref_name }}"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
          context: ./tools
          file: ./image/Dockerfile
          platforms: linux/amd64,linux/arm64
