name: Sign Docker Image

on:
  workflow_dispatch:
    inputs:
      digest:
        description: 'Docker image digest'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Install Cosign
        run: |
          curl -O -L https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
          mv cosign-linux-amd64 /usr/local/bin/cosign
          chmod +x /usr/local/bin/cosign
      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign -y --key cosign.key ${{ vars.DOCKER_USER }}/cloud-tools@${{ steps.build-docker.outputs.digest }}
